server:
  port: 8002
spring:
  application:
    name: user-provider

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: user-provider8002
