server:
  port: 8003
spring:
  application:
    #应用名，在eureka注册中心显示的服务名
    name: user-provider

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    # 不同的实例id
    instance-id: user-provider8003