server:
  port: 8080

eureka:
  client:
    # 是否需要将自己注册到Eureka-Server中
    register-with-eureka: false
    # 获取服务提供者的地址信息 默认为true
    fetch-registry: true
    # 设置注册中心的地址
    service-url:
      defaultZone: http://localhost:7001/eureka/